// contracts_slice.ts
import { createSlice, PayloadAction } from "@reduxjs/toolkit";
import { fetchContracts, ContractsResponse, Contract } from "./contracts_thunk"; // Import types and thunk

// Interface for pagination data within the state
interface ContractPaginationState {
  currentPage: number;
  perPage: number;
  totalItems: number;
  totalPages: number;
}

// Interface for the overall contracts state
interface ContractsState {
  data: {
    current_page: number;
    data: Contract[];
    first_page_url: string;
    from: number | null;
    last_page: number;
    last_page_url: string;
    links: {
      url: string | null;
      label: string;
      active: boolean;
    }[];
    next_page_url: string | null;
    path: string;
    per_page: number;
    prev_page_url: string | null;
    to: number | null;
    total: number;
  } | null;
  totalContracts: number | null;
  totalInvoice: number | null;
  totalPaidContract: number | null;
  totalUnpaidContract: number | null;
  loading: boolean;
  error: string | null;
  success: boolean;
  pagination: ContractPaginationState;
}

// Initial state for the contracts slice
const initialState: ContractsState = {
  data: null,
  totalContracts: null,
  totalInvoice: null,
  totalPaidContract: null,
  totalUnpaidContract: null,
  loading: false,
  error: null,
  success: false,
  pagination: {
    currentPage: 1,
    perPage: 10,
    totalItems: 0,
    totalPages: 1,
  },
};

// Create the contracts Redux slice
const contractsSlice = createSlice({
  name: "contracts", // Slice name
  initialState, // Initial state
  reducers: {
    // Reducer to reset the state to its initial values
    resetContractsState: () => initialState,
    // Reducer to set the current page for pagination
    setCurrentPage: (state, action: PayloadAction<number>) => {
      if (state.data) {
        state.data.current_page = action.payload;
      }
      state.pagination.currentPage = action.payload;
    },
  },
  extraReducers: (builder) => {
    builder
      // Handle pending state of fetchContracts thunk
      .addCase(fetchContracts.pending, (state) => {
        state.loading = true; // Set loading to true
        state.error = null; // Clear any previous errors
        state.success = false; // Set success to false
      })
      // Handle fulfilled state of fetchContracts thunk
      .addCase(
        fetchContracts.fulfilled,
        (state, action: PayloadAction<ContractsResponse>) => {
          state.loading = false; // Set loading to false
          state.success = action.payload.success; // Set success based on API response
          state.data = action.payload.contract_list; // Store the main contract list data
          state.totalContracts = action.payload.total_contracts;
          state.totalInvoice = action.payload.total_invoice;
          state.totalPaidContract = action.payload.total_paid_contract;
          state.totalUnpaidContract = action.payload.total_unpaid_contract;
          // Update pagination details from the API response
          state.pagination = {
            currentPage: action.payload.contract_list.current_page,
            perPage: action.payload.contract_list.per_page,
            totalItems: action.payload.contract_list.total,
            totalPages: action.payload.contract_list.last_page,
          };
        }
      )
      // Handle rejected state of fetchContracts thunk
      .addCase(fetchContracts.rejected, (state, action) => {
        state.loading = false; // Set loading to false
        // Set error message from payload or a default message
        state.error = action.payload?.message || "Failed to fetch contracts";
        state.success = false; // Set success to false
      });
  },
});

// Export actions generated by createSlice
export const { resetContractsState, setCurrentPage } = contractsSlice.actions;

// Export the reducer
export default contractsSlice.reducer;

// Selector to easily access pagination data from the Redux store
export const selectContractPagination = (state: { getcontracts: ContractsState }) =>
  state.getcontracts.pagination;

// Selector to easily access the contract list data from the Redux store
export const selectContractList = (state: { getcontracts: ContractsState }) =>
  state.getcontracts.data?.data;

// Selectors for the summary totals
export const selectTotalContracts = (state: { getcontracts: ContractsState }) =>
  state.getcontracts.totalContracts;

export const selectTotalInvoice = (state: { getcontracts: ContractsState }) =>
  state.getcontracts.totalInvoice;

export const selectTotalPaidContract = (state: { getcontracts: ContractsState }) =>
  state.getcontracts.totalPaidContract;

export const selectTotalUnpaidContract = (state: { getcontracts: ContractsState }) =>
  state.getcontracts.totalUnpaidContract;
