// career_view_slice.ts
import { createSlice, PayloadAction } from "@reduxjs/toolkit";
import { fetchCareerById, CareerDetail, CareerViewResponse } from "./career_view_thunk";

// Interface for the overall career view state
interface CareerViewState {
  career: CareerDetail | null;
  loading: boolean;
  error: string | null;
  success: boolean;
}

// Initial state for the career view slice
const initialState: CareerViewState = {
  career: null,
  loading: false,
  error: null,
  success: false,
};

// Create the career view Redux slice
const careerViewSlice = createSlice({
  name: "career_view", // Slice name
  initialState, // Initial state
  reducers: {
    // Reducer to reset the state to its initial values
    resetCareerViewState: () => initialState,
  },
  extraReducers: (builder) => {
    builder
      // Handle pending state of fetchCareerById thunk
      .addCase(fetchCareerById.pending, (state) => {
        state.loading = true; 
        state.error = null; 
        state.success = false; 
      })
      // Handle fulfilled state of fetchCareerById thunk
      .addCase(
        fetchCareerById.fulfilled,
        (state, action: PayloadAction<CareerViewResponse>) => {
          state.loading = false; 
          state.success = action.payload.success; 
          state.career = action.payload.career; 
        }
      )
      // Handle rejected state of fetchCareerById thunk
      .addCase(fetchCareerById.rejected, (state, action) => {
        state.loading = false; // Set loading to false
        // Set error message from payload or a default message
        state.error = action.payload?.message || "Failed to fetch career details";
        state.success = false; // Set success to false
      });
  },
});

// Export actions generated by createSlice
export const { resetCareerViewState } = careerViewSlice.actions;

// Export the reducer
export default careerViewSlice.reducer;

// Selector to easily access the career detail data from the Redux store
export const selectCareerDetail = (state: { getcareerview: CareerViewState }) =>
  state.getcareerview.career;
